name: '$(Date:yyyy-MM-dd).$(Rev:r)'
jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - checkout: self
    lfs: true

  - script: |
      pip3 install "aqtinstall==0.8b1"
      python -m aqt install 5.12.7 windows desktop win64_msvc2017_64
      echo ##vso[task.prependpath]$(Build.SourcesDirectory)\5.12.7\msvc2017_64\bin
    displayName: 'Install Qt'

  - script: |
      env
      call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      qmake
      nmake
    displayName: 'Build qView'
    
  - script: |
      cd bin
      windeployqt qView.exe --no-compiler-runtime
      rename qView.exe "qView-nightly.$(Build.BuildNumber).exe"
    displayName: 'Deploy qView'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'bin'
      artifactName: 'qView-nightly-win64.$(Build.BuildNumber)'
    displayName: 'Publish build artifact'

- job: macOS
  pool:
    vmImage: 'macOS-10.15'
  steps:
  - checkout: self
    lfs: true

  - script: |
      pip3 install "aqtinstall==0.8b1"
      python3 -m aqt install 5.12.7 mac desktop
      echo '##vso[task.prependpath]$(Build.SourcesDirectory)/5.12.7/clang_64/bin'
    displayName: 'Install Qt'

  - script: |
      qmake
      make
    displayName: 'Build qView'

  - script: |
      cd bin
      macdeployqt qView.app/
      mv qView.app 'qView-nightly.$(Build-BuildNumber)'
    displayName: 'Deploy qView'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'bin'
      artifactName: 'qView-nightly-macOS.$(Build.BuildNumber)'
    displayName: 'Publish build artifact'
