
variables:
  nightlyDefines: 'DEFINES+=NIGHTLY=$(Build.BuildNumber)'
  nightlyString: '-nightly'

name: '$(Date:yyyy-MM-dd).$(Rev:r)'
jobs:
- job: Build

  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-16.04'
        deployLinux: 'true'
      macos:
        imageName: 'macOS-10.15'
      win64:
        imageName: 'windows-2019'
      qt59:
        imageName: 'ubuntu-18.04'
        dontPublish: 'true'

  pool:
    vmImage: $(imageName)

  steps:
  - checkout: self

  - template: ci/install-qt.yml

  - template: ci/build.yml
    parameters:
      defines: $(nightlyDefines)
    
  - template: ci/deploy.yml
    parameters:
      linuxdeployqt: 

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'bin'
      artifactName: 'qView$(nightlyString)-$(Agent.JobName).$(Build.BuildNumber)'
    condition: and(succeeded(), ne(variables['dontPublish'], 'true'))
    displayName: 'Publish build artifact'

