parameters:
- name: defines
  type: string
- name: arch
  type: string
  default: 'win64_msvc2017_64'

steps:
- script: |
    set "arch=${{ parameters.arch }}"
    call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\%arch:~3,2%.bat"
    qmake ${{ parameters.defines }}
    nmake
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'Build qView (Windows)'

- script: |
    qmake ${{ parameters.defines }}
    make
  condition: ne( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'Build qView (Unix)'
  set "arch=win64_msvc2017_64"